/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.fsm;

import fr.univcotedazur.polytech.si4.fsm.project.ITimer;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class FSMStatemachine implements IFSMStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private SCInterfaceOperationCallback operationCallback;
		
		public synchronized void setSCInterfaceOperationCallback(
				SCInterfaceOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
		private boolean b_Coffe;
		
		
		public void raiseB_Coffe() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							b_Coffe = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean b_Expresso;
		
		
		public void raiseB_Expresso() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							b_Expresso = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean b_Tea;
		
		
		public void raiseB_Tea() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							b_Tea = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean s_Sugar;
		
		
		public void raiseS_Sugar() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							s_Sugar = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean s_Size;
		
		
		public void raiseS_Size() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							s_Size = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean s_Temp;
		
		
		public void raiseS_Temp() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							s_Temp = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean c_050;
		
		
		public void raiseC_050() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							c_050 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean c_025;
		
		
		public void raiseC_025() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							c_025 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean c_010;
		
		
		public void raiseC_010() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							c_010 = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean c_NFC;
		
		
		public void raiseC_NFC() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							c_NFC = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean b_Cancel;
		
		
		public void raiseB_Cancel() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							b_Cancel = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cup_Taken;
		
		
		public void raiseCup_Taken() {
			synchronized(FSMStatemachine.this) {
				inEventQueue.add(
					new Runnable() {
						@Override
						public void run() {
							cup_Taken = true;
							singleCycle();
						}
					}
				);
				runCycle();
			}
		}
		
		private boolean cancel;
		
		
		public boolean isRaisedCancel() {
			synchronized(FSMStatemachine.this) {
				return cancel;
			}
		}
		
		protected void raiseCancel() {
			synchronized(FSMStatemachine.this) {
				cancel = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCancelRaised();
				}
			}
		}
		
		private boolean reset;
		
		
		public boolean isRaisedReset() {
			synchronized(FSMStatemachine.this) {
				return reset;
			}
		}
		
		protected void raiseReset() {
			synchronized(FSMStatemachine.this) {
				reset = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onResetRaised();
				}
			}
		}
		
		private boolean preparing;
		
		
		public boolean isRaisedPreparing() {
			synchronized(FSMStatemachine.this) {
				return preparing;
			}
		}
		
		protected void raisePreparing() {
			synchronized(FSMStatemachine.this) {
				preparing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPreparingRaised();
				}
			}
		}
		
		private boolean crushing;
		
		
		public boolean isRaisedCrushing() {
			synchronized(FSMStatemachine.this) {
				return crushing;
			}
		}
		
		protected void raiseCrushing() {
			synchronized(FSMStatemachine.this) {
				crushing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCrushingRaised();
				}
			}
		}
		
		private boolean endCrushing;
		
		
		public boolean isRaisedEndCrushing() {
			synchronized(FSMStatemachine.this) {
				return endCrushing;
			}
		}
		
		protected void raiseEndCrushing() {
			synchronized(FSMStatemachine.this) {
				endCrushing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndCrushingRaised();
				}
			}
		}
		
		private boolean tamping;
		
		
		public boolean isRaisedTamping() {
			synchronized(FSMStatemachine.this) {
				return tamping;
			}
		}
		
		protected void raiseTamping() {
			synchronized(FSMStatemachine.this) {
				tamping = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onTampingRaised();
				}
			}
		}
		
		private boolean endTamping;
		
		
		public boolean isRaisedEndTamping() {
			synchronized(FSMStatemachine.this) {
				return endTamping;
			}
		}
		
		protected void raiseEndTamping() {
			synchronized(FSMStatemachine.this) {
				endTamping = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndTampingRaised();
				}
			}
		}
		
		private boolean heating;
		
		
		public boolean isRaisedHeating() {
			synchronized(FSMStatemachine.this) {
				return heating;
			}
		}
		
		protected void raiseHeating() {
			synchronized(FSMStatemachine.this) {
				heating = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onHeatingRaised();
				}
			}
		}
		
		private boolean endHeating;
		
		
		public boolean isRaisedEndHeating() {
			synchronized(FSMStatemachine.this) {
				return endHeating;
			}
		}
		
		protected void raiseEndHeating() {
			synchronized(FSMStatemachine.this) {
				endHeating = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndHeatingRaised();
				}
			}
		}
		
		private boolean placingCup;
		
		
		public boolean isRaisedPlacingCup() {
			synchronized(FSMStatemachine.this) {
				return placingCup;
			}
		}
		
		protected void raisePlacingCup() {
			synchronized(FSMStatemachine.this) {
				placingCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPlacingCupRaised();
				}
			}
		}
		
		private boolean endPlacingCup;
		
		
		public boolean isRaisedEndPlacingCup() {
			synchronized(FSMStatemachine.this) {
				return endPlacingCup;
			}
		}
		
		protected void raiseEndPlacingCup() {
			synchronized(FSMStatemachine.this) {
				endPlacingCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndPlacingCupRaised();
				}
			}
		}
		
		private boolean pouringWater;
		
		
		public boolean isRaisedPouringWater() {
			synchronized(FSMStatemachine.this) {
				return pouringWater;
			}
		}
		
		protected void raisePouringWater() {
			synchronized(FSMStatemachine.this) {
				pouringWater = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPouringWaterRaised();
				}
			}
		}
		
		private boolean endPouringWater;
		
		
		public boolean isRaisedEndPouringWater() {
			synchronized(FSMStatemachine.this) {
				return endPouringWater;
			}
		}
		
		protected void raiseEndPouringWater() {
			synchronized(FSMStatemachine.this) {
				endPouringWater = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndPouringWaterRaised();
				}
			}
		}
		
		private boolean pouringSugar;
		
		
		public boolean isRaisedPouringSugar() {
			synchronized(FSMStatemachine.this) {
				return pouringSugar;
			}
		}
		
		protected void raisePouringSugar() {
			synchronized(FSMStatemachine.this) {
				pouringSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPouringSugarRaised();
				}
			}
		}
		
		private boolean endPouringSugar;
		
		
		public boolean isRaisedEndPouringSugar() {
			synchronized(FSMStatemachine.this) {
				return endPouringSugar;
			}
		}
		
		protected void raiseEndPouringSugar() {
			synchronized(FSMStatemachine.this) {
				endPouringSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndPouringSugarRaised();
				}
			}
		}
		
		private boolean infusing;
		
		
		public boolean isRaisedInfusing() {
			synchronized(FSMStatemachine.this) {
				return infusing;
			}
		}
		
		protected void raiseInfusing() {
			synchronized(FSMStatemachine.this) {
				infusing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onInfusingRaised();
				}
			}
		}
		
		private boolean endInfusing;
		
		
		public boolean isRaisedEndInfusing() {
			synchronized(FSMStatemachine.this) {
				return endInfusing;
			}
		}
		
		protected void raiseEndInfusing() {
			synchronized(FSMStatemachine.this) {
				endInfusing = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndInfusingRaised();
				}
			}
		}
		
		private boolean removingBag;
		
		
		public boolean isRaisedRemovingBag() {
			synchronized(FSMStatemachine.this) {
				return removingBag;
			}
		}
		
		protected void raiseRemovingBag() {
			synchronized(FSMStatemachine.this) {
				removingBag = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onRemovingBagRaised();
				}
			}
		}
		
		private boolean endRemovingBag;
		
		
		public boolean isRaisedEndRemovingBag() {
			synchronized(FSMStatemachine.this) {
				return endRemovingBag;
			}
		}
		
		protected void raiseEndRemovingBag() {
			synchronized(FSMStatemachine.this) {
				endRemovingBag = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndRemovingBagRaised();
				}
			}
		}
		
		private boolean puttingTea;
		
		
		public boolean isRaisedPuttingTea() {
			synchronized(FSMStatemachine.this) {
				return puttingTea;
			}
		}
		
		protected void raisePuttingTea() {
			synchronized(FSMStatemachine.this) {
				puttingTea = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPuttingTeaRaised();
				}
			}
		}
		
		private boolean endPuttingTea;
		
		
		public boolean isRaisedEndPuttingTea() {
			synchronized(FSMStatemachine.this) {
				return endPuttingTea;
			}
		}
		
		protected void raiseEndPuttingTea() {
			synchronized(FSMStatemachine.this) {
				endPuttingTea = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndPuttingTeaRaised();
				}
			}
		}
		
		private boolean drinkReady;
		
		
		public boolean isRaisedDrinkReady() {
			synchronized(FSMStatemachine.this) {
				return drinkReady;
			}
		}
		
		protected void raiseDrinkReady() {
			synchronized(FSMStatemachine.this) {
				drinkReady = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDrinkReadyRaised();
				}
			}
		}
		
		private boolean cleanning;
		
		
		public boolean isRaisedCleanning() {
			synchronized(FSMStatemachine.this) {
				return cleanning;
			}
		}
		
		protected void raiseCleanning() {
			synchronized(FSMStatemachine.this) {
				cleanning = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCleanningRaised();
				}
			}
		}
		
		private boolean endCleanning;
		
		
		public boolean isRaisedEndCleanning() {
			synchronized(FSMStatemachine.this) {
				return endCleanning;
			}
		}
		
		protected void raiseEndCleanning() {
			synchronized(FSMStatemachine.this) {
				endCleanning = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onEndCleanningRaised();
				}
			}
		}
		
		private boolean progressBar;
		
		
		public boolean isRaisedProgressBar() {
			synchronized(FSMStatemachine.this) {
				return progressBar;
			}
		}
		
		protected void raiseProgressBar() {
			synchronized(FSMStatemachine.this) {
				progressBar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onProgressBarRaised();
				}
			}
		}
		
		private long price;
		
		public synchronized long getPrice() {
			synchronized(FSMStatemachine.this) {
				return price;
			}
		}
		
		public void setPrice(long value) {
			synchronized(FSMStatemachine.this) {
				this.price = value;
			}
		}
		
		private long money;
		
		public synchronized long getMoney() {
			synchronized(FSMStatemachine.this) {
				return money;
			}
		}
		
		public void setMoney(long value) {
			synchronized(FSMStatemachine.this) {
				this.money = value;
			}
		}
		
		private boolean water;
		
		public synchronized boolean getWater() {
			synchronized(FSMStatemachine.this) {
				return water;
			}
		}
		
		public void setWater(boolean value) {
			synchronized(FSMStatemachine.this) {
				this.water = value;
			}
		}
		
		private boolean sugar;
		
		public synchronized boolean getSugar() {
			synchronized(FSMStatemachine.this) {
				return sugar;
			}
		}
		
		public void setSugar(boolean value) {
			synchronized(FSMStatemachine.this) {
				this.sugar = value;
			}
		}
		
		private long aPercent;
		
		public synchronized long getAPercent() {
			synchronized(FSMStatemachine.this) {
				return aPercent;
			}
		}
		
		public void setAPercent(long value) {
			synchronized(FSMStatemachine.this) {
				this.aPercent = value;
			}
		}
		
		private boolean cupIsTaken;
		
		public synchronized boolean getCupIsTaken() {
			synchronized(FSMStatemachine.this) {
				return cupIsTaken;
			}
		}
		
		public void setCupIsTaken(boolean value) {
			synchronized(FSMStatemachine.this) {
				this.cupIsTaken = value;
			}
		}
		
		private boolean cleanIsDone;
		
		public synchronized boolean getCleanIsDone() {
			synchronized(FSMStatemachine.this) {
				return cleanIsDone;
			}
		}
		
		public void setCleanIsDone(boolean value) {
			synchronized(FSMStatemachine.this) {
				this.cleanIsDone = value;
			}
		}
		
		protected void clearEvents() {
			b_Coffe = false;
			b_Expresso = false;
			b_Tea = false;
			s_Sugar = false;
			s_Size = false;
			s_Temp = false;
			c_050 = false;
			c_025 = false;
			c_010 = false;
			c_NFC = false;
			b_Cancel = false;
			cup_Taken = false;
		}
		protected void clearOutEvents() {
		
		cancel = false;
		reset = false;
		preparing = false;
		crushing = false;
		endCrushing = false;
		tamping = false;
		endTamping = false;
		heating = false;
		endHeating = false;
		placingCup = false;
		endPlacingCup = false;
		pouringWater = false;
		endPouringWater = false;
		pouringSugar = false;
		endPouringSugar = false;
		infusing = false;
		endInfusing = false;
		removingBag = false;
		endRemovingBag = false;
		puttingTea = false;
		endPuttingTea = false;
		drinkReady = false;
		cleanning = false;
		endCleanning = false;
		progressBar = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		machine_Order,
		machine_Order_Select_Drink_select,
		machine_Order_Select_Drink_select_Selecting_Chosen,
		machine_Order_Select_Drink_select_Selecting_Waiting,
		machine_Order_Option_Waiting,
		machine_Order_Payment_Waiting,
		machine_Order_Time_Waiting,
		machine_Order_Time_Running,
		machine_Serving,
		machine_Serving_Serving_Heating_and_Cup,
		machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp,
		machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing,
		machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping,
		machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit,
		machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup,
		machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag,
		machine_Serving_Serving_Heating_and_Cup_Cup_Exit,
		machine_Serving_Serving_Water_and_Sugar,
		machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water,
		machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar,
		machine_Serving_Serving_Waiting,
		machine_Serving_Serving_Infusing,
		machine_Serving_Serving_Remove_bag,
		machine_cleaning,
		$NullState$
	};
	
	private final State[] stateVector = new State[4];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[12];
	
	private Queue<Runnable> internalEventQueue = new LinkedList<Runnable>();
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isRunningCycle = false;
	private boolean startTimer;
	private boolean accept;
	private boolean clean;
	private boolean newOrder;
	public FSMStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		if (this.sCInterface.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCInterface must be set.");
		}
		
		for (int i = 0; i < 4; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setPrice(0);
		
		sCInterface.setMoney(0);
		
		sCInterface.setWater(false);
		
		sCInterface.setSugar(false);
		
		sCInterface.setAPercent(0);
		
		sCInterface.setCupIsTaken(false);
		
		sCInterface.setCleanIsDone(false);
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_Machine_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		
		if (isRunningCycle) {
			return;
		}
		isRunningCycle = true;
		
		clearOutEvents();
	
		Runnable task = getNextEvent();
		if (task == null) {
			task = getDefaultEvent();
		}
		
		while (task != null) {
			task.run();
			clearEvents();
			task = getNextEvent();
		}
		
		isRunningCycle = false;
	}
	
	protected synchronized void singleCycle() {
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
				case machine_Order_Select_Drink_select_Selecting_Chosen:
					machine_Order_Select_Drink_select_Selecting_Chosen_react(true);
					break;
				case machine_Order_Select_Drink_select_Selecting_Waiting:
					machine_Order_Select_Drink_select_Selecting_Waiting_react(true);
					break;
				case machine_Order_Option_Waiting:
					machine_Order_Option_Waiting_react(true);
					break;
				case machine_Order_Payment_Waiting:
					machine_Order_Payment_Waiting_react(true);
					break;
				case machine_Order_Time_Waiting:
					machine_Order_Time_Waiting_react(true);
					break;
				case machine_Order_Time_Running:
					machine_Order_Time_Running_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp:
					machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing:
					machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping:
					machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit:
					machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup:
					machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag:
					machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag_react(true);
					break;
				case machine_Serving_Serving_Heating_and_Cup_Cup_Exit:
					machine_Serving_Serving_Heating_and_Cup_Cup_Exit_react(true);
					break;
				case machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water:
					machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water_react(true);
					break;
				case machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar:
					machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar_react(true);
					break;
				case machine_Serving_Serving_Waiting:
					machine_Serving_Serving_Waiting_react(true);
					break;
				case machine_Serving_Serving_Infusing:
					machine_Serving_Serving_Infusing_react(true);
					break;
				case machine_Serving_Serving_Remove_bag:
					machine_Serving_Serving_Remove_bag_react(true);
					break;
				case machine_cleaning:
					machine_cleaning_react(true);
					break;
			default:
				// $NullState$
			}
		}
	}
	
	protected Runnable getNextEvent() {
		if(!internalEventQueue.isEmpty()) {
			return internalEventQueue.poll();
		}
		if(!inEventQueue.isEmpty()) {
			return inEventQueue.poll();
		}
		return null;
	}
	
	protected Runnable getDefaultEvent() {
		return new Runnable() {
			@Override
			public void run() {
				singleCycle();
			}
		};
	}
	
	public synchronized void exit() {
		exitSequence_Machine();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$||stateVector[3] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		startTimer = false;
		accept = false;
		clean = false;
		newOrder = false;
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case machine_Order:
			return stateVector[0].ordinal() >= State.
					machine_Order.ordinal()&& stateVector[0].ordinal() <= State.machine_Order_Time_Running.ordinal();
		case machine_Order_Select_Drink_select:
			return stateVector[0].ordinal() >= State.
					machine_Order_Select_Drink_select.ordinal()&& stateVector[0].ordinal() <= State.machine_Order_Select_Drink_select_Selecting_Waiting.ordinal();
		case machine_Order_Select_Drink_select_Selecting_Chosen:
			return stateVector[0] == State.machine_Order_Select_Drink_select_Selecting_Chosen;
		case machine_Order_Select_Drink_select_Selecting_Waiting:
			return stateVector[0] == State.machine_Order_Select_Drink_select_Selecting_Waiting;
		case machine_Order_Option_Waiting:
			return stateVector[1] == State.machine_Order_Option_Waiting;
		case machine_Order_Payment_Waiting:
			return stateVector[2] == State.machine_Order_Payment_Waiting;
		case machine_Order_Time_Waiting:
			return stateVector[3] == State.machine_Order_Time_Waiting;
		case machine_Order_Time_Running:
			return stateVector[3] == State.machine_Order_Time_Running;
		case machine_Serving:
			return stateVector[0].ordinal() >= State.
					machine_Serving.ordinal()&& stateVector[0].ordinal() <= State.machine_Serving_Serving_Remove_bag.ordinal();
		case machine_Serving_Serving_Heating_and_Cup:
			return stateVector[0].ordinal() >= State.
					machine_Serving_Serving_Heating_and_Cup.ordinal()&& stateVector[0].ordinal() <= State.machine_Serving_Serving_Heating_and_Cup_Cup_Exit.ordinal();
		case machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp:
			return stateVector[0] == State.machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing:
			return stateVector[1] == State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping:
			return stateVector[1] == State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit:
			return stateVector[1] == State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup:
			return stateVector[2] == State.machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag:
			return stateVector[2] == State.machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Exit:
			return stateVector[2] == State.machine_Serving_Serving_Heating_and_Cup_Cup_Exit;
		case machine_Serving_Serving_Water_and_Sugar:
			return stateVector[0].ordinal() >= State.
					machine_Serving_Serving_Water_and_Sugar.ordinal()&& stateVector[0].ordinal() <= State.machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar.ordinal();
		case machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water:
			return stateVector[0] == State.machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water;
		case machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar:
			return stateVector[1] == State.machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar;
		case machine_Serving_Serving_Waiting:
			return stateVector[0] == State.machine_Serving_Serving_Waiting;
		case machine_Serving_Serving_Infusing:
			return stateVector[0] == State.machine_Serving_Serving_Infusing;
		case machine_Serving_Serving_Remove_bag:
			return stateVector[0] == State.machine_Serving_Serving_Remove_bag;
		case machine_cleaning:
			return stateVector[0] == State.machine_cleaning;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
				singleCycle();
			}
		});
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	private void raiseStartTimer() {
	
		internalEventQueue.add( new Runnable() {
			@Override public void run() {
				startTimer = true;					
				singleCycle();
			}
		});
	}
	
	private void raiseAccept() {
	
		internalEventQueue.add( new Runnable() {
			@Override public void run() {
				accept = true;					
				singleCycle();
			}
		});
	}
	
	private void raiseClean() {
	
		internalEventQueue.add( new Runnable() {
			@Override public void run() {
				clean = true;					
				singleCycle();
			}
		});
	}
	
	private void raiseNewOrder() {
	
		internalEventQueue.add( new Runnable() {
			@Override public void run() {
				newOrder = true;					
				singleCycle();
			}
		});
	}
	
	public synchronized void raiseB_Coffe() {
		sCInterface.raiseB_Coffe();
	}
	
	public synchronized void raiseB_Expresso() {
		sCInterface.raiseB_Expresso();
	}
	
	public synchronized void raiseB_Tea() {
		sCInterface.raiseB_Tea();
	}
	
	public synchronized void raiseS_Sugar() {
		sCInterface.raiseS_Sugar();
	}
	
	public synchronized void raiseS_Size() {
		sCInterface.raiseS_Size();
	}
	
	public synchronized void raiseS_Temp() {
		sCInterface.raiseS_Temp();
	}
	
	public synchronized void raiseC_050() {
		sCInterface.raiseC_050();
	}
	
	public synchronized void raiseC_025() {
		sCInterface.raiseC_025();
	}
	
	public synchronized void raiseC_010() {
		sCInterface.raiseC_010();
	}
	
	public synchronized void raiseC_NFC() {
		sCInterface.raiseC_NFC();
	}
	
	public synchronized void raiseB_Cancel() {
		sCInterface.raiseB_Cancel();
	}
	
	public synchronized void raiseCup_Taken() {
		sCInterface.raiseCup_Taken();
	}
	
	public synchronized boolean isRaisedCancel() {
		return sCInterface.isRaisedCancel();
	}
	
	public synchronized boolean isRaisedReset() {
		return sCInterface.isRaisedReset();
	}
	
	public synchronized boolean isRaisedPreparing() {
		return sCInterface.isRaisedPreparing();
	}
	
	public synchronized boolean isRaisedCrushing() {
		return sCInterface.isRaisedCrushing();
	}
	
	public synchronized boolean isRaisedEndCrushing() {
		return sCInterface.isRaisedEndCrushing();
	}
	
	public synchronized boolean isRaisedTamping() {
		return sCInterface.isRaisedTamping();
	}
	
	public synchronized boolean isRaisedEndTamping() {
		return sCInterface.isRaisedEndTamping();
	}
	
	public synchronized boolean isRaisedHeating() {
		return sCInterface.isRaisedHeating();
	}
	
	public synchronized boolean isRaisedEndHeating() {
		return sCInterface.isRaisedEndHeating();
	}
	
	public synchronized boolean isRaisedPlacingCup() {
		return sCInterface.isRaisedPlacingCup();
	}
	
	public synchronized boolean isRaisedEndPlacingCup() {
		return sCInterface.isRaisedEndPlacingCup();
	}
	
	public synchronized boolean isRaisedPouringWater() {
		return sCInterface.isRaisedPouringWater();
	}
	
	public synchronized boolean isRaisedEndPouringWater() {
		return sCInterface.isRaisedEndPouringWater();
	}
	
	public synchronized boolean isRaisedPouringSugar() {
		return sCInterface.isRaisedPouringSugar();
	}
	
	public synchronized boolean isRaisedEndPouringSugar() {
		return sCInterface.isRaisedEndPouringSugar();
	}
	
	public synchronized boolean isRaisedInfusing() {
		return sCInterface.isRaisedInfusing();
	}
	
	public synchronized boolean isRaisedEndInfusing() {
		return sCInterface.isRaisedEndInfusing();
	}
	
	public synchronized boolean isRaisedRemovingBag() {
		return sCInterface.isRaisedRemovingBag();
	}
	
	public synchronized boolean isRaisedEndRemovingBag() {
		return sCInterface.isRaisedEndRemovingBag();
	}
	
	public synchronized boolean isRaisedPuttingTea() {
		return sCInterface.isRaisedPuttingTea();
	}
	
	public synchronized boolean isRaisedEndPuttingTea() {
		return sCInterface.isRaisedEndPuttingTea();
	}
	
	public synchronized boolean isRaisedDrinkReady() {
		return sCInterface.isRaisedDrinkReady();
	}
	
	public synchronized boolean isRaisedCleanning() {
		return sCInterface.isRaisedCleanning();
	}
	
	public synchronized boolean isRaisedEndCleanning() {
		return sCInterface.isRaisedEndCleanning();
	}
	
	public synchronized boolean isRaisedProgressBar() {
		return sCInterface.isRaisedProgressBar();
	}
	
	public synchronized long getPrice() {
		return sCInterface.getPrice();
	}
	
	public synchronized void setPrice(long value) {
		sCInterface.setPrice(value);
	}
	
	public synchronized long getMoney() {
		return sCInterface.getMoney();
	}
	
	public synchronized void setMoney(long value) {
		sCInterface.setMoney(value);
	}
	
	public synchronized boolean getWater() {
		return sCInterface.getWater();
	}
	
	public synchronized void setWater(boolean value) {
		sCInterface.setWater(value);
	}
	
	public synchronized boolean getSugar() {
		return sCInterface.getSugar();
	}
	
	public synchronized void setSugar(boolean value) {
		sCInterface.setSugar(value);
	}
	
	public synchronized long getAPercent() {
		return sCInterface.getAPercent();
	}
	
	public synchronized void setAPercent(long value) {
		sCInterface.setAPercent(value);
	}
	
	public synchronized boolean getCupIsTaken() {
		return sCInterface.getCupIsTaken();
	}
	
	public synchronized void setCupIsTaken(boolean value) {
		sCInterface.setCupIsTaken(value);
	}
	
	public synchronized boolean getCleanIsDone() {
		return sCInterface.getCleanIsDone();
	}
	
	public synchronized void setCleanIsDone(boolean value) {
		sCInterface.setCleanIsDone(value);
	}
	
	private boolean check_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0_tr0_tr0() {
		return sCInterface.operationCallback.isExpresso();
	}
	
	private boolean check_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0_tr0_tr0() {
		return sCInterface.operationCallback.isTea();
	}
	
	private boolean check_Machine_Serving_Serving__choice_0_tr0_tr0() {
		return sCInterface.operationCallback.isTea();
	}
	
	private void effect_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0_tr0() {
		sCInterface.raiseCrushing();
		
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing_default();
	}
	
	private void effect_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0_tr1() {
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit_default();
	}
	
	private void effect_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0_tr0() {
		sCInterface.raisePuttingTea();
		
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag_default();
	}
	
	private void effect_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0_tr1() {
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit_default();
	}
	
	private void effect_Machine_Serving_Serving__choice_0_tr0() {
		sCInterface.raiseInfusing();
		
		enterSequence_Machine_Serving_Serving_Infusing_default();
	}
	
	private void effect_Machine_Serving_Serving__choice_0_tr1() {
		enterSequence_Machine_Serving_Serving_Waiting_default();
	}
	
	/* Entry action for state 'Chosen'. */
	private void entryAction_Machine_Order_Select_Drink_select_Selecting_Chosen() {
		sCInterface.setPrice(sCInterface.operationCallback.newPrice());
		
		raiseAccept();
		
		raiseStartTimer();
	}
	
	/* Entry action for state 'Waiting'. */
	private void entryAction_Machine_Order_Select_Drink_select_Selecting_Waiting() {
		sCInterface.setMoney(0);
	}
	
	/* Entry action for state 'Waiting'. */
	private void entryAction_Machine_Order_Payment_Waiting() {
		raiseAccept();
	}
	
	/* Entry action for state 'Running'. */
	private void entryAction_Machine_Order_Time_Running() {
		timer.setTimer(this, 0, (10 * 1000), false);
	}
	
	/* Entry action for state 'Serving'. */
	private void entryAction_Machine_Serving() {
		timer.setTimer(this, 1, sCInterface.getAPercent(), true);
	}
	
	/* Entry action for state 'Waiting Temp'. */
	private void entryAction_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp() {
		timer.setTimer(this, 2, (sCInterface.operationCallback.getHeatingTime() * 1000), false);
		
		sCInterface.raiseHeating();
	}
	
	/* Entry action for state 'Grain crushing'. */
	private void entryAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing() {
		timer.setTimer(this, 3, (sCInterface.operationCallback.getCrushingTime() * 1000), false);
	}
	
	/* Entry action for state 'Grain tamping'. */
	private void entryAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping() {
		timer.setTimer(this, 4, ((sCInterface.operationCallback.getCrushingTime() / 4) * 1000), false);
	}
	
	/* Entry action for state 'Placing cup'. */
	private void entryAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup() {
		timer.setTimer(this, 5, (3 * 1000), false);
		
		sCInterface.raisePlacingCup();
		
		sCInterface.setCupIsTaken(false);
	}
	
	/* Entry action for state 'Putting Bag'. */
	private void entryAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag() {
		timer.setTimer(this, 6, (3 * 1000), false);
	}
	
	/* Entry action for state 'Water'. */
	private void entryAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water() {
		timer.setTimer(this, 7, (sCInterface.operationCallback.getPouringWater() * 1000), false);
		
		sCInterface.raisePouringWater();
	}
	
	/* Entry action for state 'Sugar'. */
	private void entryAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar() {
		timer.setTimer(this, 8, (sCInterface.operationCallback.getPouringSugar() * 1000), false);
		
		sCInterface.raisePouringSugar();
	}
	
	/* Entry action for state 'Waiting'. */
	private void entryAction_Machine_Serving_Serving_Waiting() {
		raiseClean();
		
		sCInterface.raiseDrinkReady();
	}
	
	/* Entry action for state 'Infusing'. */
	private void entryAction_Machine_Serving_Serving_Infusing() {
		timer.setTimer(this, 9, (sCInterface.operationCallback.getInfusingTime() * 1000), false);
	}
	
	/* Entry action for state 'Remove bag'. */
	private void entryAction_Machine_Serving_Serving_Remove_bag() {
		timer.setTimer(this, 10, (3 * 1000), false);
		
		sCInterface.raiseRemovingBag();
	}
	
	/* Entry action for state 'cleaning'. */
	private void entryAction_Machine_cleaning() {
		timer.setTimer(this, 11, (5 * 1000), false);
		
		sCInterface.raiseCleanning();
	}
	
	/* Exit action for state 'Running'. */
	private void exitAction_Machine_Order_Time_Running() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Serving'. */
	private void exitAction_Machine_Serving() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Waiting Temp'. */
	private void exitAction_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'Grain crushing'. */
	private void exitAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'Grain tamping'. */
	private void exitAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'Placing cup'. */
	private void exitAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup() {
		timer.unsetTimer(this, 5);
	}
	
	/* Exit action for state 'Putting Bag'. */
	private void exitAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag() {
		timer.unsetTimer(this, 6);
	}
	
	/* Exit action for state 'Water'. */
	private void exitAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water() {
		timer.unsetTimer(this, 7);
	}
	
	/* Exit action for state 'Sugar'. */
	private void exitAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar() {
		timer.unsetTimer(this, 8);
	}
	
	/* Exit action for state 'Infusing'. */
	private void exitAction_Machine_Serving_Serving_Infusing() {
		timer.unsetTimer(this, 9);
	}
	
	/* Exit action for state 'Remove bag'. */
	private void exitAction_Machine_Serving_Serving_Remove_bag() {
		timer.unsetTimer(this, 10);
	}
	
	/* Exit action for state 'cleaning'. */
	private void exitAction_Machine_cleaning() {
		timer.unsetTimer(this, 11);
	}
	
	/* 'default' enter sequence for state Order */
	private void enterSequence_Machine_Order_default() {
		enterSequence_Machine_Order_Select_default();
		enterSequence_Machine_Order_Option_default();
		enterSequence_Machine_Order_Payment_default();
		enterSequence_Machine_Order_Time_default();
	}
	
	/* 'default' enter sequence for state Drink_select */
	private void enterSequence_Machine_Order_Select_Drink_select_default() {
		enterSequence_Machine_Order_Select_Drink_select_Selecting_default();
	}
	
	/* 'default' enter sequence for state Chosen */
	private void enterSequence_Machine_Order_Select_Drink_select_Selecting_Chosen_default() {
		entryAction_Machine_Order_Select_Drink_select_Selecting_Chosen();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Order_Select_Drink_select_Selecting_Chosen;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Machine_Order_Select_Drink_select_Selecting_Waiting_default() {
		entryAction_Machine_Order_Select_Drink_select_Selecting_Waiting();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Order_Select_Drink_select_Selecting_Waiting;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Machine_Order_Option_Waiting_default() {
		nextStateIndex = 1;
		stateVector[1] = State.machine_Order_Option_Waiting;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Machine_Order_Payment_Waiting_default() {
		entryAction_Machine_Order_Payment_Waiting();
		nextStateIndex = 2;
		stateVector[2] = State.machine_Order_Payment_Waiting;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Machine_Order_Time_Waiting_default() {
		nextStateIndex = 3;
		stateVector[3] = State.machine_Order_Time_Waiting;
	}
	
	/* 'default' enter sequence for state Running */
	private void enterSequence_Machine_Order_Time_Running_default() {
		entryAction_Machine_Order_Time_Running();
		nextStateIndex = 3;
		stateVector[3] = State.machine_Order_Time_Running;
	}
	
	/* 'default' enter sequence for state Serving */
	private void enterSequence_Machine_Serving_default() {
		entryAction_Machine_Serving();
		enterSequence_Machine_Serving_Serving_default();
	}
	
	/* 'default' enter sequence for state Heating and Cup */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_default() {
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_default();
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_default();
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_default();
	}
	
	/* 'default' enter sequence for state Waiting Temp */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp_default() {
		entryAction_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp;
	}
	
	/* 'default' enter sequence for state Grain crushing */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing_default() {
		entryAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing();
		nextStateIndex = 1;
		stateVector[1] = State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing;
	}
	
	/* 'default' enter sequence for state Grain tamping */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping_default() {
		entryAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping();
		nextStateIndex = 1;
		stateVector[1] = State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping;
	}
	
	/* 'default' enter sequence for state exit */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit_default() {
		nextStateIndex = 1;
		stateVector[1] = State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit;
	}
	
	/* 'default' enter sequence for state Placing cup */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup_default() {
		entryAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup();
		nextStateIndex = 2;
		stateVector[2] = State.machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup;
	}
	
	/* 'default' enter sequence for state Putting Bag */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag_default() {
		entryAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag();
		nextStateIndex = 2;
		stateVector[2] = State.machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag;
	}
	
	/* 'default' enter sequence for state Exit */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit_default() {
		nextStateIndex = 2;
		stateVector[2] = State.machine_Serving_Serving_Heating_and_Cup_Cup_Exit;
	}
	
	/* 'default' enter sequence for state Water and Sugar */
	private void enterSequence_Machine_Serving_Serving_Water_and_Sugar_default() {
		enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_default();
		enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_default();
	}
	
	/* 'default' enter sequence for state Water */
	private void enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water_default() {
		entryAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water;
	}
	
	/* 'default' enter sequence for state Sugar */
	private void enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar_default() {
		entryAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar();
		nextStateIndex = 1;
		stateVector[1] = State.machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Machine_Serving_Serving_Waiting_default() {
		entryAction_Machine_Serving_Serving_Waiting();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Serving_Serving_Waiting;
	}
	
	/* 'default' enter sequence for state Infusing */
	private void enterSequence_Machine_Serving_Serving_Infusing_default() {
		entryAction_Machine_Serving_Serving_Infusing();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Serving_Serving_Infusing;
	}
	
	/* 'default' enter sequence for state Remove bag */
	private void enterSequence_Machine_Serving_Serving_Remove_bag_default() {
		entryAction_Machine_Serving_Serving_Remove_bag();
		nextStateIndex = 0;
		stateVector[0] = State.machine_Serving_Serving_Remove_bag;
	}
	
	/* 'default' enter sequence for state cleaning */
	private void enterSequence_Machine_cleaning_default() {
		entryAction_Machine_cleaning();
		nextStateIndex = 0;
		stateVector[0] = State.machine_cleaning;
	}
	
	/* 'default' enter sequence for region Machine */
	private void enterSequence_Machine_default() {
		react_Machine__entry_Default();
	}
	
	/* 'default' enter sequence for region Select */
	private void enterSequence_Machine_Order_Select_default() {
		react_Machine_Order_Select__entry_Default();
	}
	
	/* 'default' enter sequence for region Selecting */
	private void enterSequence_Machine_Order_Select_Drink_select_Selecting_default() {
		react_Machine_Order_Select_Drink_select_Selecting_default();
	}
	
	/* 'default' enter sequence for region Option */
	private void enterSequence_Machine_Order_Option_default() {
		react_Machine_Order_Option__entry_Default();
	}
	
	/* 'default' enter sequence for region Payment */
	private void enterSequence_Machine_Order_Payment_default() {
		react_Machine_Order_Payment__entry_Default();
	}
	
	/* 'default' enter sequence for region Time */
	private void enterSequence_Machine_Order_Time_default() {
		react_Machine_Order_Time__entry_Default();
	}
	
	/* 'default' enter sequence for region Serving */
	private void enterSequence_Machine_Serving_Serving_default() {
		react_Machine_Serving_Serving_default();
	}
	
	/* 'default' enter sequence for region Heating */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_default() {
		react_Machine_Serving_Serving_Heating_and_Cup_Heating__entry_Default();
	}
	
	/* 'default' enter sequence for region Grain crushing */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_default() {
		react_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__entry_Default();
	}
	
	/* 'default' enter sequence for region Cup */
	private void enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_default() {
		react_Machine_Serving_Serving_Heating_and_Cup_Cup__entry_Default();
	}
	
	/* 'default' enter sequence for region Pouring water */
	private void enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_default() {
		react_Machine_Serving_Serving_Water_and_Sugar_Pouring_water__entry_Default();
	}
	
	/* 'default' enter sequence for region Pouring sugar */
	private void enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_default() {
		react_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar__entry_Default();
	}
	
	/* Default exit sequence for state Order */
	private void exitSequence_Machine_Order() {
		exitSequence_Machine_Order_Select();
		exitSequence_Machine_Order_Option();
		exitSequence_Machine_Order_Payment();
		exitSequence_Machine_Order_Time();
	}
	
	/* Default exit sequence for state Chosen */
	private void exitSequence_Machine_Order_Select_Drink_select_Selecting_Chosen() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Machine_Order_Select_Drink_select_Selecting_Waiting() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Machine_Order_Option_Waiting() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Machine_Order_Payment_Waiting() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Machine_Order_Time_Waiting() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state Running */
	private void exitSequence_Machine_Order_Time_Running() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_Machine_Order_Time_Running();
	}
	
	/* Default exit sequence for state Serving */
	private void exitSequence_Machine_Serving() {
		exitSequence_Machine_Serving_Serving();
		exitAction_Machine_Serving();
	}
	
	/* Default exit sequence for state Heating and Cup */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup() {
		exitSequence_Machine_Serving_Serving_Heating_and_Cup_Heating();
		exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing();
		exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup();
	}
	
	/* Default exit sequence for state Waiting Temp */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp();
	}
	
	/* Default exit sequence for state Grain crushing */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing();
	}
	
	/* Default exit sequence for state Grain tamping */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping();
	}
	
	/* Default exit sequence for state exit */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state Placing cup */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup();
	}
	
	/* Default exit sequence for state Putting Bag */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag();
	}
	
	/* Default exit sequence for state Exit */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
	}
	
	/* Default exit sequence for state Water and Sugar */
	private void exitSequence_Machine_Serving_Serving_Water_and_Sugar() {
		exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water();
		exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar();
	}
	
	/* Default exit sequence for state Water */
	private void exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water();
	}
	
	/* Default exit sequence for state Sugar */
	private void exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar();
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Machine_Serving_Serving_Waiting() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Infusing */
	private void exitSequence_Machine_Serving_Serving_Infusing() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Infusing();
	}
	
	/* Default exit sequence for state Remove bag */
	private void exitSequence_Machine_Serving_Serving_Remove_bag() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Machine_Serving_Serving_Remove_bag();
	}
	
	/* Default exit sequence for state cleaning */
	private void exitSequence_Machine_cleaning() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Machine_cleaning();
	}
	
	/* Default exit sequence for region Machine */
	private void exitSequence_Machine() {
		switch (stateVector[0]) {
		case machine_Order_Select_Drink_select_Selecting_Chosen:
			exitSequence_Machine_Order_Select_Drink_select_Selecting_Chosen();
			break;
		case machine_Order_Select_Drink_select_Selecting_Waiting:
			exitSequence_Machine_Order_Select_Drink_select_Selecting_Waiting();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp();
			break;
		case machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water:
			exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water();
			break;
		case machine_Serving_Serving_Waiting:
			exitSequence_Machine_Serving_Serving_Waiting();
			exitAction_Machine_Serving();
			break;
		case machine_Serving_Serving_Infusing:
			exitSequence_Machine_Serving_Serving_Infusing();
			exitAction_Machine_Serving();
			break;
		case machine_Serving_Serving_Remove_bag:
			exitSequence_Machine_Serving_Serving_Remove_bag();
			exitAction_Machine_Serving();
			break;
		case machine_cleaning:
			exitSequence_Machine_cleaning();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case machine_Order_Option_Waiting:
			exitSequence_Machine_Order_Option_Waiting();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit();
			break;
		case machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar:
			exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar();
			exitAction_Machine_Serving();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case machine_Order_Payment_Waiting:
			exitSequence_Machine_Order_Payment_Waiting();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup();
			exitAction_Machine_Serving();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag();
			exitAction_Machine_Serving();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Exit:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit();
			exitAction_Machine_Serving();
			break;
		default:
			break;
		}
		
		switch (stateVector[3]) {
		case machine_Order_Time_Waiting:
			exitSequence_Machine_Order_Time_Waiting();
			break;
		case machine_Order_Time_Running:
			exitSequence_Machine_Order_Time_Running();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Select */
	private void exitSequence_Machine_Order_Select() {
		switch (stateVector[0]) {
		case machine_Order_Select_Drink_select_Selecting_Chosen:
			exitSequence_Machine_Order_Select_Drink_select_Selecting_Chosen();
			break;
		case machine_Order_Select_Drink_select_Selecting_Waiting:
			exitSequence_Machine_Order_Select_Drink_select_Selecting_Waiting();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Option */
	private void exitSequence_Machine_Order_Option() {
		switch (stateVector[1]) {
		case machine_Order_Option_Waiting:
			exitSequence_Machine_Order_Option_Waiting();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Payment */
	private void exitSequence_Machine_Order_Payment() {
		switch (stateVector[2]) {
		case machine_Order_Payment_Waiting:
			exitSequence_Machine_Order_Payment_Waiting();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Time */
	private void exitSequence_Machine_Order_Time() {
		switch (stateVector[3]) {
		case machine_Order_Time_Waiting:
			exitSequence_Machine_Order_Time_Waiting();
			break;
		case machine_Order_Time_Running:
			exitSequence_Machine_Order_Time_Running();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Serving */
	private void exitSequence_Machine_Serving_Serving() {
		switch (stateVector[0]) {
		case machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp();
			break;
		case machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water:
			exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water();
			break;
		case machine_Serving_Serving_Waiting:
			exitSequence_Machine_Serving_Serving_Waiting();
			break;
		case machine_Serving_Serving_Infusing:
			exitSequence_Machine_Serving_Serving_Infusing();
			break;
		case machine_Serving_Serving_Remove_bag:
			exitSequence_Machine_Serving_Serving_Remove_bag();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit();
			break;
		case machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar:
			exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Exit:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Heating */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Heating() {
		switch (stateVector[0]) {
		case machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Grain crushing */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing() {
		switch (stateVector[1]) {
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Cup */
	private void exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup() {
		switch (stateVector[2]) {
		case machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag();
			break;
		case machine_Serving_Serving_Heating_and_Cup_Cup_Exit:
			exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Pouring water */
	private void exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water() {
		switch (stateVector[0]) {
		case machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water:
			exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Pouring sugar */
	private void exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar() {
		switch (stateVector[1]) {
		case machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar:
			exitSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar();
			break;
		default:
			break;
		}
	}
	
	/* The reactions of state null. */
	private void react_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0() {
		if (check_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0_tr0_tr0()) {
			effect_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0_tr0();
		} else {
			effect_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0_tr1();
		}
	}
	
	/* The reactions of state null. */
	private void react_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0() {
		if (check_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0_tr0_tr0()) {
			effect_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0_tr0();
		} else {
			effect_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0_tr1();
		}
	}
	
	/* The reactions of state null. */
	private void react_Machine_Serving_Serving__choice_0() {
		if (check_Machine_Serving_Serving__choice_0_tr0_tr0()) {
			effect_Machine_Serving_Serving__choice_0_tr0();
		} else {
			effect_Machine_Serving_Serving__choice_0_tr1();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine__entry_Default() {
		enterSequence_Machine_Order_default();
	}
	
	/* Default react sequence for initial entry default */
	private void react_Machine_Order_Select_Drink_select_Selecting_default() {
		enterSequence_Machine_Order_Select_Drink_select_Selecting_Waiting_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Order_Select__entry_Default() {
		enterSequence_Machine_Order_Select_Drink_select_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Order_Option__entry_Default() {
		enterSequence_Machine_Order_Option_Waiting_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Order_Payment__entry_Default() {
		enterSequence_Machine_Order_Payment_Waiting_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Order_Time__entry_Default() {
		enterSequence_Machine_Order_Time_Waiting_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Serving_Serving_Heating_and_Cup_Heating__entry_Default() {
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__entry_Default() {
		react_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing__choice_0();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Serving_Serving_Heating_and_Cup_Cup__entry_Default() {
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup_default();
	}
	
	/* Default react sequence for initial entry default */
	private void react_Machine_Serving_Serving_default() {
		enterSequence_Machine_Serving_Serving_Heating_and_Cup_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Serving_Serving_Water_and_Sugar_Pouring_water__entry_Default() {
		enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar__entry_Default() {
		enterSequence_Machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar_default();
	}
	
	/* The reactions of state null. */
	private void react_Machine_Serving_Serving__sync0() {
		enterSequence_Machine_Serving_Serving_Water_and_Sugar_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean machine_Order_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.b_Cancel) {
				exitSequence_Machine_Order();
				sCInterface.raiseCancel();
				
				enterSequence_Machine_Order_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean machine_Order_Select_Drink_select_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean machine_Order_Select_Drink_select_Selecting_Chosen_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.b_Coffe || (sCInterface.b_Expresso || sCInterface.b_Tea))) {
				exitSequence_Machine_Order_Select_Drink_select_Selecting_Chosen();
				enterSequence_Machine_Order_Select_Drink_select_Selecting_Chosen_default();
				machine_Order_Select_Drink_select_react(false);
			} else {
				if (((accept) && (sCInterface.getMoney()>=sCInterface.getPrice()))) {
					exitSequence_Machine_Order();
					sCInterface.raisePreparing();
					
					sCInterface.setAPercent(sCInterface.operationCallback.getPercent());
					
					sCInterface.setCleanIsDone(false);
					
					enterSequence_Machine_Serving_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = machine_Order_Select_Drink_select_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Order_Select_Drink_select_Selecting_Waiting_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.b_Coffe || (sCInterface.b_Expresso || sCInterface.b_Tea))) {
				exitSequence_Machine_Order_Select_Drink_select_Selecting_Waiting();
				enterSequence_Machine_Order_Select_Drink_select_Selecting_Chosen_default();
				machine_Order_Select_Drink_select_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Order_Select_Drink_select_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Order_Option_Waiting_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.s_Sugar || (sCInterface.s_Size || sCInterface.s_Temp))) {
				exitSequence_Machine_Order_Option_Waiting();
				raiseStartTimer();
				
				enterSequence_Machine_Order_Option_Waiting_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_Order_Payment_Waiting_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.c_050 || (sCInterface.c_025 || (sCInterface.c_010 || sCInterface.c_NFC)))) {
				exitSequence_Machine_Order_Payment_Waiting();
				raiseStartTimer();
				
				sCInterface.setMoney(sCInterface.operationCallback.currentMoney());
				
				enterSequence_Machine_Order_Payment_Waiting_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_Order_Time_Waiting_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (startTimer) {
				exitSequence_Machine_Order_Time_Waiting();
				enterSequence_Machine_Order_Time_Running_default();
				machine_Order_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Order_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Order_Time_Running_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (startTimer) {
				exitSequence_Machine_Order_Time_Running();
				enterSequence_Machine_Order_Time_Running_default();
				machine_Order_react(false);
			} else {
				if (((timeEvents[0]) && ((sCInterface.getPrice()!=0 || sCInterface.getMoney()!=0)))) {
					exitSequence_Machine_Order();
					sCInterface.raiseCancel();
					
					enterSequence_Machine_Order_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = machine_Order_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cup_Taken) {
				exitSequence_Machine_Serving();
				sCInterface.setCupIsTaken(true);
				
				enterSequence_Machine_cleaning_default();
				react();
			} else {
				if (clean) {
					exitSequence_Machine_Serving();
					enterSequence_Machine_cleaning_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			if (timeEvents[1]) {
				sCInterface.raiseProgressBar();
			}
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = machine_Serving_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((((timeEvents[2] && isStateActive(State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit)) && true) && isStateActive(State.machine_Serving_Serving_Heating_and_Cup_Cup_Exit)) && true)) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup();
				sCInterface.raiseEndHeating();
				
				react_Machine_Serving_Serving__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[3]) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_crushing();
				sCInterface.raiseTamping();
				
				sCInterface.raiseEndCrushing();
				
				enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_Grain_tamping();
				sCInterface.raiseEndTamping();
				
				enterSequence_Machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((((true && isStateActive(State.machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp)) && timeEvents[2]) && isStateActive(State.machine_Serving_Serving_Heating_and_Cup_Cup_Exit)) && true)) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup();
				sCInterface.raiseEndHeating();
				
				react_Machine_Serving_Serving__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[5]) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Placing_cup();
				sCInterface.raiseEndPlacingCup();
				
				react_Machine_Serving_Serving_Heating_and_Cup_Cup__choice_0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Serving_Serving_Heating_and_Cup_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[6]) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Putting_Bag();
				sCInterface.raiseEndPuttingTea();
				
				enterSequence_Machine_Serving_Serving_Heating_and_Cup_Cup_Exit_default();
				machine_Serving_Serving_Heating_and_Cup_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Serving_Serving_Heating_and_Cup_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Heating_and_Cup_Cup_Exit_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((((true && isStateActive(State.machine_Serving_Serving_Heating_and_Cup_Heating_Waiting_Temp)) && timeEvents[2]) && isStateActive(State.machine_Serving_Serving_Heating_and_Cup_Grain_crushing_exit)) && true)) {
				exitSequence_Machine_Serving_Serving_Heating_and_Cup();
				sCInterface.raiseEndHeating();
				
				react_Machine_Serving_Serving__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Serving_Serving_Heating_and_Cup_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Water_and_Sugar_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((sCInterface.getWater() && sCInterface.getSugar())) {
				exitSequence_Machine_Serving_Serving_Water_and_Sugar();
				sCInterface.setWater(false);
				
				sCInterface.setSugar(false);
				
				react_Machine_Serving_Serving__choice_0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Serving_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Water_and_Sugar_Pouring_water_Water_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			if (timeEvents[7]) {
				sCInterface.raiseEndPouringWater();
				
				sCInterface.setWater(true);
			}
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Water_and_Sugar_Pouring_sugar_Sugar_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			if (timeEvents[8]) {
				sCInterface.raiseEndPouringSugar();
				
				sCInterface.setSugar(true);
			}
			did_transition = machine_Serving_Serving_Water_and_Sugar_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Waiting_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = machine_Serving_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Infusing_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[9]) {
				exitSequence_Machine_Serving_Serving_Infusing();
				sCInterface.raiseEndInfusing();
				
				enterSequence_Machine_Serving_Serving_Remove_bag_default();
				machine_Serving_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Serving_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_Serving_Serving_Remove_bag_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[10]) {
				exitSequence_Machine_Serving_Serving_Remove_bag();
				sCInterface.raiseEndRemovingBag();
				
				enterSequence_Machine_Serving_Serving_Waiting_default();
				machine_Serving_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_Serving_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_cleaning_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (((newOrder) && ((sCInterface.getCupIsTaken() && sCInterface.getCleanIsDone())))) {
				exitSequence_Machine_cleaning();
				sCInterface.raiseReset();
				
				enterSequence_Machine_Order_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			if (timeEvents[11]) {
				sCInterface.setCleanIsDone(true);
				
				raiseNewOrder();
				
				sCInterface.raiseEndCleanning();
			}
			if (sCInterface.cup_Taken) {
				sCInterface.setCupIsTaken(true);
				
				raiseNewOrder();
			}
			did_transition = react();
		}
		return did_transition;
	}
	
}
