/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.fsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IFSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseB_drink();
		
		public void raiseS_Slide();
		
		public void raiseB_option();
		
		public void raiseC_coin();
		
		public void raiseC_NFC();
		
		public void raiseB_Cancel();
		
		public void raiseCup_Taken();
		
		public void raiseB_Cup();
		
		public boolean isRaisedCancel();
		
		public boolean isRaisedReset();
		
		public boolean isRaisedPreparing();
		
		public boolean isRaisedCoffeePod();
		
		public boolean isRaisedEndCoffeePod();
		
		public boolean isRaisedCrushing();
		
		public boolean isRaisedEndCrushing();
		
		public boolean isRaisedTamping();
		
		public boolean isRaisedEndTamping();
		
		public boolean isRaisedHeating();
		
		public boolean isRaisedEndHeating();
		
		public boolean isRaisedPlacingCup();
		
		public boolean isRaisedEndPlacingCup();
		
		public boolean isRaisedPouringWater();
		
		public boolean isRaisedEndPouringWater();
		
		public boolean isRaisedPouringSugar();
		
		public boolean isRaisedEndPouringSugar();
		
		public boolean isRaisedInfusing();
		
		public boolean isRaisedEndInfusing();
		
		public boolean isRaisedRemovingBag();
		
		public boolean isRaisedEndRemovingBag();
		
		public boolean isRaisedPuttingTea();
		
		public boolean isRaisedEndPuttingTea();
		
		public boolean isRaisedDrinkReady();
		
		public boolean isRaisedCleanning();
		
		public boolean isRaisedEndCleanning();
		
		public boolean isRaisedProgressBar();
		
		public boolean isRaisedPouringMapleSyrup();
		
		public boolean isRaisedEndPouringMapleSyrup();
		
		public boolean isRaisedPouringSoup();
		
		public boolean isRaisedPouringSpice();
		
		public boolean isRaisedEndPouringSpice();
		
		public boolean isRaisedPouringCroutons();
		
		public boolean isRaisedEndPouringCroutons();
		
		public boolean isRaisedPouringVanilla();
		
		public boolean isRaisedMixVanilla();
		
		public boolean isRaisedEndVanilla();
		
		public boolean isRaisedPouringMilkCloud();
		
		public boolean isRaisedEndMilkCloud();
		
		public boolean isRaisedNitrogen();
		
		public boolean isRaisedEndNitrogen();
		
		public boolean isRaisedACup();
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public long getMoney();
		
		public void setMoney(long value);
		
		public boolean getWater();
		
		public void setWater(boolean value);
		
		public boolean getSugar();
		
		public void setSugar(boolean value);
		
		public long getAPercent();
		
		public void setAPercent(long value);
		
		public boolean getCupIsTaken();
		
		public void setCupIsTaken(boolean value);
		
		public boolean getCleanIsDone();
		
		public void setCleanIsDone(boolean value);
		
		public boolean getCup();
		
		public void setCup(boolean value);
		
	public List<SCInterfaceListener> getListeners();
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceListener {
	
		public void onCancelRaised();
		public void onResetRaised();
		public void onPreparingRaised();
		public void onCoffeePodRaised();
		public void onEndCoffeePodRaised();
		public void onCrushingRaised();
		public void onEndCrushingRaised();
		public void onTampingRaised();
		public void onEndTampingRaised();
		public void onHeatingRaised();
		public void onEndHeatingRaised();
		public void onPlacingCupRaised();
		public void onEndPlacingCupRaised();
		public void onPouringWaterRaised();
		public void onEndPouringWaterRaised();
		public void onPouringSugarRaised();
		public void onEndPouringSugarRaised();
		public void onInfusingRaised();
		public void onEndInfusingRaised();
		public void onRemovingBagRaised();
		public void onEndRemovingBagRaised();
		public void onPuttingTeaRaised();
		public void onEndPuttingTeaRaised();
		public void onDrinkReadyRaised();
		public void onCleanningRaised();
		public void onEndCleanningRaised();
		public void onProgressBarRaised();
		public void onPouringMapleSyrupRaised();
		public void onEndPouringMapleSyrupRaised();
		public void onPouringSoupRaised();
		public void onPouringSpiceRaised();
		public void onEndPouringSpiceRaised();
		public void onPouringCroutonsRaised();
		public void onEndPouringCroutonsRaised();
		public void onPouringVanillaRaised();
		public void onMixVanillaRaised();
		public void onEndVanillaRaised();
		public void onPouringMilkCloudRaised();
		public void onEndMilkCloudRaised();
		public void onNitrogenRaised();
		public void onEndNitrogenRaised();
		public void onACupRaised();
		}
	
	public interface SCInterfaceOperationCallback {
	
		public long newPrice();
		
		public long currentMoney();
		
		public long getHeatingTime();
		
		public long getCrushingTime();
		
		public long getPouringWater();
		
		public long getPouringSugar();
		
		public long getPouringSpices();
		
		public long getInfusingTime();
		
		public long getNitrogenTime();
		
		public boolean isCoffee();
		
		public boolean isExpresso();
		
		public boolean isTea();
		
		public boolean isIceTea();
		
		public boolean isSoup();
		
		public boolean isSugar();
		
		public boolean isMapleSyrup();
		
		public boolean isCroutons();
		
		public boolean isVanilla();
		
		public boolean isMilkCloud();
		
		public long getPercent();
		
	}
	
	public SCInterface getSCInterface();
	
}
