/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.fsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IFSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseB_Coffe();
		
		public void raiseB_Expresso();
		
		public void raiseB_Tea();
		
		public void raiseS_Sugar();
		
		public void raiseS_Size();
		
		public void raiseS_Temp();
		
		public void raiseC_050();
		
		public void raiseC_025();
		
		public void raiseC_010();
		
		public void raiseC_NFC();
		
		public void raiseB_Cancel();
		
		public void raiseCup_Taken();
		
		public boolean isRaisedOnCancel();
		
		public boolean isRaisedPreparing();
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public long getMoney();
		
		public void setMoney(long value);
		
	public List<SCInterfaceListener> getListeners();
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceListener {
	
		public void onOnCancelRaised();
		public void onPreparingRaised();
		}
	
	public interface SCInterfaceOperationCallback {
	
		public long newPrice();
		
		public long currentMoney();
		
	}
	
	public SCInterface getSCInterface();
	
}
