/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.fsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IFSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseB_Coffe();
		
		public void raiseB_Expresso();
		
		public void raiseB_Tea();
		
		public void raiseS_Sugar();
		
		public void raiseS_Size();
		
		public void raiseS_Temp();
		
		public void raiseC_050();
		
		public void raiseC_025();
		
		public void raiseC_010();
		
		public void raiseC_NFC();
		
		public void raiseB_Cancel();
		
		public void raiseCup_Taken();
		
		public boolean isRaisedOnCancel();
		
		public boolean isRaisedOnReset();
		
		public boolean isRaisedPreparing();
		
		public boolean isRaisedOnCrushing();
		
		public boolean isRaisedOnTamping();
		
		public boolean isRaisedOnHeating();
		
		public boolean isRaisedOnPlacingCup();
		
		public boolean isRaisedOnPouringWater();
		
		public boolean isRaisedOnPouringShugar();
		
		public boolean isRaisedOnInfusing();
		
		public boolean isRaisedOnRemovingBag();
		
		public boolean isRaisedOnPuttingTea();
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public long getMoney();
		
		public void setMoney(long value);
		
		public long getHeatingTime();
		
		public void setHeatingTime(long value);
		
		public long getPouringWater();
		
		public void setPouringWater(long value);
		
		public long getPouringShugar();
		
		public void setPouringShugar(long value);
		
		public long getCrushingTime();
		
		public void setCrushingTime(long value);
		
		public long getInfusingTime();
		
		public void setInfusingTime(long value);
		
	public List<SCInterfaceListener> getListeners();
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceListener {
	
		public void onOnCancelRaised();
		public void onOnResetRaised();
		public void onPreparingRaised();
		public void onOnCrushingRaised();
		public void onOnTampingRaised();
		public void onOnHeatingRaised();
		public void onOnPlacingCupRaised();
		public void onOnPouringWaterRaised();
		public void onOnPouringShugarRaised();
		public void onOnInfusingRaised();
		public void onOnRemovingBagRaised();
		public void onOnPuttingTeaRaised();
		}
	
	public interface SCInterfaceOperationCallback {
	
		public long newPrice();
		
		public long currentMoney();
		
		public long getHeatingTime();
		
		public long getCrushingTime();
		
		public long getPouringWater();
		
		public long getPouringShugar();
		
		public long getInfusingTime();
		
		public boolean isExpresso();
		
		public boolean isTea();
		
	}
	
	public SCInterface getSCInterface();
	
}
